# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c21f4708d1aa0a8634fed134b387a65380b6a7a011883070e7ae9d6dec8608f7541dc58b05affb20a57f5dd73e38e87c79b55b6f18710d0a194d447a577249bd

test:
  secret_key_base: 9b0a6f5949e9128158a596478fb44a9a7522c1366ad18a69b289c4e9a6efd8432d930679ac19e0f62e65cb79955382840f570657245b3b4929240db2d20cc525

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
